/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recibosc60agia;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpression;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import recibosc60agia.utils.Utils;

/**
 *
 * @author vPalomo
 */
public class InicioRecibosC601xPath extends javax.swing.JFrame {

    /**
     * Creates new form InicioRecibosC60
     */
    public String totalTXT = "";
    public String totalCSV = "";
    

    public InicioRecibosC601xPath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jFileText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextTributo = new javax.swing.JTextField();
        jTextEjercicio = new javax.swing.JTextField();
        jTextPeriodo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextConcepto = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jFileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileTextActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Procesar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generar fichero padrón desde Recibos C60 - Cronos to GIA");

        jTextTributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTributoActionPerformed(evt);
            }
        });
        jTextTributo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTributoKeyTyped(evt);
            }
        });

        jTextEjercicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextEjercicioKeyTyped(evt);
            }
        });

        jTextPeriodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPeriodoKeyTyped(evt);
            }
        });

        jLabel2.setText("Código de tributo:");

        jLabel3.setText("Ejercicio del padrón:");

        jLabel4.setText("Periodo del padrón:");

        jLabel5.setText("Código del concepto:");

        jTextConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextConceptoKeyTyped(evt);
            }
        });

        jButton4.setText("Guardar fichero GIA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Guardar listado cuentas (IBAN)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFileText, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(392, 392, 392))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextEjercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                        .addComponent(jTextTributo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextPeriodo))
                                    .addGap(52, 52, 52)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jTextConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML", "xml");
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jFileText.setText(file.getAbsolutePath());

            //This is where a real application would open the file.
            //log.append("Opening: " + file.getName() + "." + newline);
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        File file = new File(jFileText.getText());

        String recibo = "";
        try {
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(file);
            NodeList nList = doc.getElementsByTagName("DrctDbtTxInf");
            System.out.println("Numero de nodos: " + nList.getLength());
            for (int i = 0; i < nList.getLength(); i++) {
                recibo = generarCadenaTXT(nList.item(i), i); 
                recibo = Utils.rellenaN(jTextTributo.getText(), 3)
                        + Utils.rellenaN(jTextEjercicio.getText(), 4)
                        + Utils.rellenaN(jTextPeriodo.getText(), 2)
                        + Utils.rellenaN("" + (i + 1), 6) + recibo;
                System.out.println(recibo);
                totalTXT += recibo + "\n";
            }
            //System.out.println("Total: "+total);
            doc.getDocumentElement().normalize();
            guardarTXT();
            guardarCVS();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextTributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTributoActionPerformed

    private void jTextTributoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTributoKeyTyped
        JTextField texto = (JTextField) evt.getSource();
        if (texto.getText().length() == 3)
            evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_jTextTributoKeyTyped

    private void jTextEjercicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEjercicioKeyTyped
        JTextField texto = (JTextField) evt.getSource();
        if (texto.getText().length() == 4)
            evt.consume();
    }//GEN-LAST:event_jTextEjercicioKeyTyped

    private void jTextPeriodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPeriodoKeyTyped
        JTextField texto = (JTextField) evt.getSource();
        if (texto.getText().length() == 2)
            evt.consume();
    }//GEN-LAST:event_jTextPeriodoKeyTyped

    private void jTextConceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextConceptoKeyTyped
        JTextField texto = (JTextField) evt.getSource();
        if (texto.getText().length() == 4)
            evt.consume();
    }//GEN-LAST:event_jTextConceptoKeyTyped

    private void guardarTXT(){
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TXT", "txt");
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter);
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            //jFileText.setText(file.getAbsolutePath());
            try (BufferedWriter BW = new BufferedWriter(new FileWriter(file))) {
                BW.write(totalTXT);
                JOptionPane.showMessageDialog(this, "El archivo TXT se ha guardado correctamente");
                totalTXT="";
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error: "+e, "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        guardarTXT();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        guardarCVS();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioRecibosC601xPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioRecibosC601xPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioRecibosC601xPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioRecibosC601xPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioRecibosC601xPath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jFileText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextConcepto;
    private javax.swing.JTextField jTextEjercicio;
    private javax.swing.JTextField jTextPeriodo;
    private javax.swing.JTextField jTextTributo;
    // End of variables declaration//GEN-END:variables

    /**
     * Genera los datos del recibo que se cargará en GIA menos los 5 primeros datos.
     * @param nodo
     * @param indice
     * @return 
     */
    private String generarCadenaTXT(Node nodo, int indice) {
        
        String result = "";
        String aux = "";
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document nuevoDoc = builder.newDocument();
            //Node nodoOriginal = nuevoDoc.getDocumentElement();
            Node nodoImportado = nuevoDoc.importNode(nodo, true);
            nuevoDoc.appendChild(nodoImportado);

            totalCSV+=(indice+1);
            
            //DNI
            //NodeList nListAUX = nuevoDoc.getElementsByTagName("EndToEndId");
            //aux = nListAUX.item(0).getFirstChild().getNodeValue().substring(0, 9);
            XPathFactory xpathFactory = XPathFactory.newInstance();
            XPath xpath = xpathFactory.newXPath();
            String expression = "//Id/PrvtId/Othr/Id";
            XPathExpression xpathExpression;
            NodeList nodes=null;
            try {
                xpathExpression = xpath.compile(expression);
                nodes = (NodeList) xpathExpression.evaluate(nuevoDoc, XPathConstants.NODESET);
            } catch (XPathExpressionException ex) {
                Logger.getLogger(InicioRecibosC601xPath.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            //NodeList nListAUX = nuevoDoc.getElementsByTagName("Id");
            //aux = nListAUX.item(0).getFirstChild().getNodeValue();
            if(nodes.item(0)!=null){
                //aux=nodes.item(0).getTextContent();
                aux=nodes.item(0).getFirstChild().getNodeValue();
                if (nodes.getLength() > 1) {
                    JOptionPane.showMessageDialog(null, "Existen dos DNI en un recibo. (Existen 2 nodos 'EndToEndID' dentor del mismo recibo en el XML del cuaderno 19 elegido. Indice: " + indice + ")");
                }
            }else{
                aux="";
            }
            result += Utils.rellenaDer(aux, " ", 20);
            totalCSV+=";"+aux;
            
            
            //Nombre y Apellidos
            NodeList nListAUX = nuevoDoc.getElementsByTagName("Nm");
            aux = nListAUX.item(0).getFirstChild().getNodeValue();
            aux=aux.trim();
            if (nListAUX.getLength() > 1) {
                JOptionPane.showMessageDialog(null, "Existen dos nombre en un recibo. (Existen 2 nodos 'Nm' dentor del mismo recibo en el XML del cuaderno 19 elegido. Indice: " + indice + ")");
            }
            result += Utils.rellenaDer(aux, " ", 50);
            totalCSV+=";"+aux;
            
            //IBAN (no se pasa a GIA, es para generar un excel con los datos del tercero y su numero de cuenta.
            nListAUX = nuevoDoc.getElementsByTagName("IBAN");
            aux = nListAUX.item(0).getFirstChild().getNodeValue();
            if (nListAUX.getLength() > 1) {
                JOptionPane.showMessageDialog(null, "Existen dos IBAN en un recibo. (Existen 2 nodos 'IBAN' dentor del mismo recibo en el XML del cuaderno 19 elegido. Indice: " + indice + ")");
            }
            //result += Utils.rellenaDer(aux, " ", 50);
            totalCSV+=";"+aux+"\n";

            //Rellenamos 65 carateres más 
            result += Utils.rellenaA("", 5);//tipo via
            result += Utils.rellenaA("", 25);//nombre via
            result += Utils.rellenaN("", 5);//numero
            result += Utils.rellenaA("", 25);//Otra informa
            result += Utils.rellenaN("", 5);//cod postal
            result += Utils.rellenaA("", 25);//Localidad
            result += Utils.rellenaA("", 25);//Provincia

            //importe
            nListAUX = nuevoDoc.getElementsByTagName("InstdAmt");
            aux = nListAUX.item(0).getFirstChild().getNodeValue();
            if (nListAUX.getLength() > 1) {
                JOptionPane.showMessageDialog(null, "Existen dos importes en un recibo. (Existen 2 nodos 'InstdAmt' dentor del mismo recibo en el XML del cuaderno 19 elegido. Indice: " + indice + ")");
            }
            aux = aux.replace(".", "");
            result += "+" + Utils.rellenaIzq(aux, "0", 12);

            result += "NT"; //Estado

            //Fecha estado en formado aaaammdd
            nListAUX = nuevoDoc.getElementsByTagName("DtOfSgntr");
            aux = nListAUX.item(0).getFirstChild().getNodeValue();
            if (nListAUX.getLength() > 1) {
                JOptionPane.showMessageDialog(null, "Existen dos fechas para un recibo. (Existen 2 nodos 'DtOfSgntr' dentor del mismo recibo en el XML del cuaderno 19 elegido. Indice: " + indice + ")");
            }
            aux=Utils.fecha(aux); 
            result += Utils.rellenaN(aux, 8);

            //Variables 1,2,3,4,5 y 6
            nListAUX = nuevoDoc.getElementsByTagName("Ustrd");
            aux = nListAUX.item(0).getFirstChild().getNodeValue();
            if (nListAUX.getLength() > 1) {
                JOptionPane.showMessageDialog(null, "Existen dos textos del recibo para un recibo. (Existen 2 nodos 'Ustrd' dentor del mismo recibo en el XML del cuaderno 19 elegido. Indice: " + indice + ")");
            }
            result += Utils.rellenaA(aux, 180);

            //Conceptos
            //Concepto 1 mas signo
            result += Utils.rellenaN(jTextConcepto.getText(), 4);

            //importe concepto 1
            nListAUX = nuevoDoc.getElementsByTagName("InstdAmt");
            String importe = nListAUX.item(0).getFirstChild().getNodeValue();
            if (nListAUX.getLength() > 1) {
                JOptionPane.showMessageDialog(null, "Existen dos importes en un recibo. (Existen 2 nodos 'InstdAmt' dentor del mismo recibo en el XML del cuaderno 19 elegido. Indice: " + indice + ")");
            }
            importe = importe.replace(".", "");
            result += "+" + Utils.rellenaN(importe, 12);
            result += Utils.rellenaN("0", 12);

            //importe concepto 2        
            result += getCadenaConceptoVacio();
            //importe concepto 3        
            result += getCadenaConceptoVacio();
            //importe concepto 4        
            result += getCadenaConceptoVacio();
            //importe concepto 5        
            result += getCadenaConceptoVacio();
            //importe concepto 6        
            result += getCadenaConceptoVacio();
            //importe concepto 7        
            result += getCadenaConceptoVacio();
            //importe concepto 8        
            result += getCadenaConceptoVacio();
            //importe concepto 9        
            result += getCadenaConceptoVacio();
            //importe concepto 10        
            result += getCadenaConceptoVacio();
            //importe concepto 11        
            result += getCadenaConceptoVacio();
            //importe concepto 12        
            result += getCadenaConceptoVacio();
            //importe concepto 13       
            result += getCadenaConceptoVacio();
            //importe concepto 14        
            result += getCadenaConceptoVacio();
            //importe concepto 15        
            result += getCadenaConceptoVacio();
            //Importe IVA 21
            result += "+000000000000000000000000";
            //Importe IVA 10
            result += "+000000000000000000000000";
            //Importe IVA 0
            result += "+" + Utils.rellenaN(importe, 12) + "000000000000";

        } catch (ParserConfigurationException ex) {
            Logger.getLogger(InicioRecibosC601xPath.class.getName()).log(Level.SEVERE, null, ex);
        }

        return result;

    }

    public String getCadenaConceptoVacio() {
        return "0000+000000000000000000000000";
    }

    private void guardarCVS() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV", "csv");
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(filter);
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            //jFileText.setText(file.getAbsolutePath());
            try (BufferedWriter BW = new BufferedWriter(new FileWriter(file))) {
                BW.write(totalCSV);
                JOptionPane.showMessageDialog(this, "El archivo CSV se ha guardado correctamente");
                totalCSV="";
            } catch (IOException e) {
                e.printStackTrace();
            }

        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }
}
