/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package citasss.paneles;

import citasss.beans.CitaDisponibleBeans;
import citasss.beans.HorarioDisponibleBean;
import citasss.gestores.GestionCitasBD;
import citasss.gestores.GestionTrabajadorasBD;
import com.toedter.calendar.JCalendar;
import java.awt.GridLayout;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author vPalomo
 */
public class AñadeCitasDisponiblesPanel extends javax.swing.JPanel {

    /**
     * Creates new form AñadeCitasDisponiblesPanel
     */
    private JFrame padre;
    private ArrayList<JCheckBox> listaCheck;

    public AñadeCitasDisponiblesPanel(JFrame padre) {
        this.padre = padre;
        initComponents();
        cargaCheck();
    }

    public void cargaCheck() {
        listaCheck = new ArrayList<>();
        String filtroTrabajadora = comboTrabajadora.getModel().getElementAt(comboTrabajadora.getSelectedIndex()).split(" - ")[0];
        jPanel2.setLayout(new GridLayout(0, 2, 10, 10));
        jPanel2.removeAll();
        jPanel2.revalidate();
        jPanel2.repaint();
        ArrayList<HorarioDisponibleBean> listaHorarioDisp = GestionCitasBD.getListaHorarioCitas(filtroTrabajadora);
        JCheckBox check;
        for (HorarioDisponibleBean hora : listaHorarioDisp) {
            check = new JCheckBox(hora.getHorarioAntencion().substring(0, 5));
            jPanel2.add(check);
            listaCheck.add(check);
        }
        check = new JCheckBox("TODOS");
        check.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JCheckBox c = (JCheckBox) e.getSource();
                seleccionaTodo(c.isSelected());
            }
        });
        jPanel2.add(check);
        jPanel2.revalidate();  // recalcula el layout
        jPanel2.repaint();
        this.revalidate();
        this.repaint();
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.pack();   // funciona igual en JFrame y en JDialog
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTrabajadora = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFecha1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        comboTrabajadora.setModel(GestionTrabajadorasBD.getModeloComboTrabajadoras());
        comboTrabajadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTrabajadoraActionPerformed(evt);
            }
        });

        jLabel1.setText("Trabajadora");

        jButton1.setText("Calendario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar/Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(comboTrabajadora, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboTrabajadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboTrabajadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTrabajadoraActionPerformed
        cargaCheck();
    }//GEN-LAST:event_comboTrabajadoraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JCalendar dateChooser = new JCalendar();
        int opcion = JOptionPane.showConfirmDialog(this, dateChooser, "Seleccione una fecha", JOptionPane.OK_CANCEL_OPTION);

        if (opcion == JOptionPane.OK_OPTION && dateChooser.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            jTextFecha1.setText(sdf.format(dateChooser.getDate()));
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String filtroTrabajadora = comboTrabajadora.getModel().getElementAt(comboTrabajadora.getSelectedIndex()).split(" - ")[0];
        int result = 0;
        for (JCheckBox check : listaCheck) {
            if(check.isSelected()){
                result += GestionCitasBD.guardarCitaDisponible(new CitaDisponibleBeans(filtroTrabajadora, jTextFecha1.getText(), check.getText()+":00", 1));
            }else{
                System.out.println("Alguno sin seleccionar");
            }
        }
        JOptionPane.showMessageDialog(this, "Se han guardado " + result + " citas correctamente");
        cargaCheck();
        jTextFecha1.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Window w = SwingUtilities.getWindowAncestor(this);
        w.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTrabajadora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFecha1;
    // End of variables declaration//GEN-END:variables

    private void seleccionaTodo(boolean b) {
        for (JCheckBox check : listaCheck) {
            check.setSelected(b);
        }
    }
}
