/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package citasss.paneles;

import citasss.beans.ServiciosBean;
import citasss.gestores.GestionCitasBD;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vPalomo
 */
public class ServiciosPanel extends javax.swing.JPanel {

    private String idCita;
    private String idTrabajadora;
    private String idPersona;
    
    /**
     * 
     * @param idCita
     * @param idTrabajadora
     * @param idPersona 
     */
    public ServiciosPanel(String idCita, String idTrabajadora, String idPersona) {
        this.idCita=idCita;
        this.idTrabajadora=idTrabajadora;
        this.idPersona=idPersona;
        initComponents();
        ponListenerTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "idSer", "Servicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableServicios);
        if (jTableServicios.getColumnModel().getColumnCount() > 0) {
            jTableServicios.getColumnModel().getColumn(0).setResizable(false);
            jTableServicios.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableServicios.getColumnModel().getColumn(1).setResizable(false);
            jTableServicios.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        jLabel1.setText("Servicios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void ponListenerTabla() {
        JPanel padre = this;
        jTableServicios.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 1) {
                    //String idServicio = (String) jTableServicios.getValueAt(jTableServicios.getSelectedRow(), 0);
                    System.out.println("Se ha hecho un click");
                }

                if (e.getClickCount() == 2) {
                    String idServicio = (String) jTableServicios.getValueAt(jTableServicios.getSelectedRow(), 0);
                    System.out.println("Se ha hecho un click");
                    
                    //cargarCitasFecha(jTextFecha1.getText());
//                    System.out.println("Se ha hecho doble click");
//                    String idPersona =(String) jTablePersonas.getValueAt(jTablePersonas.getSelectedRow(), 0);
//                    //String id = (String) jTablePersonas.getModel().getValueAt(jTablePersonas.getSelectedRow(), 1);
//                    System.out.println("Id: " + idPersona);
                    System.out.println("Result: "+GestionCitasBD.asignarCitaDisponible(idCita,idPersona, idTrabajadora, idServicio));
                    Window w = SwingUtilities.getWindowAncestor(padre);
                    w.setVisible(false);

                }
            }
        });
    }
    private void cargarDatos() {
        ArrayList<ServiciosBean> lista=GestionCitasBD.getServicios();
        DefaultTableModel datosTabla = (DefaultTableModel) jTableServicios.getModel();
        for (int i = datosTabla.getRowCount(); i > 0; i--) {
            datosTabla.removeRow(i - 1);
        }
        lista.forEach((ser) -> {
            datosTabla.addRow(new Object[]{
                ser.getIdServicio(),
                ser.getNombreServicio()
            });
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicios;
    // End of variables declaration//GEN-END:variables
}
